services:
  app:
    container_name: app
    build: ./src
    working_dir: /opt
    tty: true
    entrypoint: ./entrypoint-app.sh
    privileged: true
    volumes:
      - ./src:/opt
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - broker
  celery:
    container_name: celery
    build: ./src
    working_dir: /opt
    tty: true
    entrypoint: ./entrypoint-celery.sh
    privileged: true
    volumes:
      - ./src:/opt
      - ./data:/data
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - broker
  broker:
    container_name: broker
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
